syntax = "proto3";

package subscription.v1;

service SubscriptionService {
    rpc GetDistinctRepos(GetDistinctReposRequest) returns (GetDistinctReposResponse) {}
    rpc GetConfirmedSubscribersByRepo(GetConfirmedSubscribersByRepoRequest) returns (GetConfirmedSubscribersByRepoResponse) {}
    rpc UpdateLastSeenTag(UpdateLastSeenTagRequest) returns (UpdateLastSeenTagResponse) {}
    rpc CountConfirmedSubscriptions(CountConfirmedSubscriptionsRequest) returns (CountConfirmedSubscriptionsResponse) {}
}

message Repo {
    string owner = 1;
    string repo = 2;
}

message GetDistinctReposRequest {}

message GetDistinctReposResponse {
    repeated Repo repos = 1;
}

message GetConfirmedSubscribersByRepoRequest {
    string owner = 1;
    string repo = 2;
}

message ConfirmedSubscriber {
    string email = 1;
    string unsub_token = 2;
    optional string last_seen_tag = 3;
}

message GetConfirmedSubscribersByRepoResponse {
    repeated ConfirmedSubscriber confirmed_subscribers = 1;
}

message UpdateLastSeenTagRequest {
    string owner = 1;
    string repo = 2;
    string tag = 3;
}

message UpdateLastSeenTagResponse {}

message CountConfirmedSubscriptionsRequest {}

message CountConfirmedSubscriptionsResponse {
    int32 count = 1;
}
